/obj/structure/retail/gun_store
	desc = "Boom! Booom!! BOOOOOOM!!!!"
	products_list = list(new /datum/data/vending_product("M1911", /obj/item/gun/ballistic/automatic/vampire/m1911, 1000),
		new /datum/data/vending_product("M1911 magazine", /obj/item/ammo_box/magazine/vamp45acp, 15),
		new	/datum/data/vending_product(".45 ACP ammo (100)", /obj/item/ammo_box/vampire/c45acp, 125),
		new /datum/data/vending_product("elite 92G", /obj/item/gun/ballistic/automatic/vampire/beretta, 700),
		new /datum/data/vending_product("92g magazine", /obj/item/ammo_box/magazine/semi9mm, 30),
		new /datum/data/vending_product("brokk 19", /obj/item/gun/ballistic/automatic/vampire/glock19, 500),
		new /datum/data/vending_product("brokk 19 magazine", /obj/item/ammo_box/magazine/glock9mm, 15),
		new /datum/data/vending_product("snub-nose revolver", /obj/item/gun/ballistic/vampire/revolver/snub, 450),
		new /datum/data/vending_product("9mm moon clip", /obj/item/ammo_box/vampire/c9mm/moonclip, 25),
		new /datum/data/vending_product("9mm ammo (100)", /obj/item/ammo_box/vampire/c9mm, 100),
		new /datum/data/vending_product("desert eagle", /obj/item/gun/ballistic/automatic/vampire/deagle, 1300),
		new /datum/data/vending_product("desert eagle magazine", /obj/item/ammo_box/magazine/m44, 50),
		new /datum/data/vending_product("magnum revolver", /obj/item/gun/ballistic/vampire/revolver, 1400),
		new /datum/data/vending_product(".44 speedloader", /obj/item/ammo_box/vampire/c44/speedloader, 40),
		new /datum/data/vending_product(".44 ammo (60)", /obj/item/ammo_box/vampire/c44, 90),
		new /datum/data/vending_product("hunting rifle", /obj/item/gun/ballistic/automatic/vampire/huntrifle, 1000),
		new /datum/data/vending_product("hunting rifle magazine, 5.56", /obj/item/ammo_box/magazine/vamp556/hunt, 40),
		new /datum/data/vending_product("5.56 ammo (60)", /obj/item/ammo_box/vampire/c556, 30),
		new	/datum/data/vending_product("5.45 ammo (60)", /obj/item/ammo_box/vampire/c545, 50),
		new /datum/data/vending_product("shotgun", /obj/item/gun/ballistic/shotgun/vampire, 900),
		new /datum/data/vending_product("12g buckshot (30)",/obj/item/ammo_box/vampire/c12g/buck, 30),
		new /datum/data/vending_product("taser", /obj/item/melee/baton/handtaser, 30),
		new /datum/data/vending_product("pepperspray", /obj/item/reagent_containers/spray/pepper, 30),
		new /datum/data/vending_product("fishing rod", /obj/item/fishing_rod),
		new /datum/data/vending_product("knife", /obj/item/melee/vampirearms/knife, 15),
		new /datum/data/vending_product("baseball bat", /obj/item/melee/vampirearms/baseball, 60),
		new /datum/data/vending_product("katana", /obj/item/melee/vampirearms/katana, 1500),
		new /datum/data/vending_product("machete", /obj/item/melee/vampirearms/machete, 100),
	)
